"""Parse the compact Telegram start payloads generated by CineLink's frontend."""

from __future__ import annotations

import re

from bot.models import ContentKind

MOVIE_PAYLOAD = re.compile(r"^m_(?P<tmdb_id>[1-9]\d*)$")
EPISODE_PAYLOAD = re.compile(
    r"^s_(?P<tmdb_id>[1-9]\d*)_s(?P<season>[1-9]\d*)_e(?P<episode>[1-9]\d*)$"
)


def parse_start_payload(payload: str) -> tuple[ContentKind, int, int | None, int | None] | None:
    """Return a validated catalog lookup key without accepting arbitrary commands."""

    movie_match = MOVIE_PAYLOAD.fullmatch(payload)
    if movie_match:
        return "movie", int(movie_match.group("tmdb_id")), None, None

    episode_match = EPISODE_PAYLOAD.fullmatch(payload)
    if episode_match:
        return (
            "episode",
            int(episode_match.group("tmdb_id")),
            int(episode_match.group("season")),
            int(episode_match.group("episode")),
        )
    return None
